spring:
  application:
    name: LSTM-power
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: qq3486965412@163.com
    password: UFSnn3J4SSKLriRU
    host: smtp.163.com
    port: 587
    protocol: smtp
    default-encoding: utf-8
    ssl:
      enabled: true
server:
  port: 8080