server:
  port: 8080

spring:
  application:
    name: LSTM-power
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: qq3486965412@163.com
    password: UFSnn3J4SSKLriRU
    host: smtp.163.com
    port: 587
    protocol: smtp
    default-encoding: utf-8
    ssl:
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lstm?&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai#
    username: root
    password: 2350852666


mybatis:
  mapper-locations: classpath:/Mappers/*.xml
  type-aliases-package: com.qiu.lstmpower.Entity

